name: "CICD for Nginx webapp using Dockerfile"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  repository: nginx-ubuntu

permissions:
  contents: read

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITUSER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/metadata-action#tags-input
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5 
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build Image
        run: |
          docker image build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest .

      # https://github.com/aquasecurity/trivy-action
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push to Docker Hub
        run: |
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:${{ steps.meta.outputs.tags }}
