name: "CICD for Nginx webapp using Dockerfile"
# Run Build, Scan, and Push GitHub workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  repository: nginx-ubuntu

permissions:
  contents: read

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extract metadata for Docker image
      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:${{ steps.meta.outputs.version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}:${{ steps.meta.outputs.version }}
