name: "CICD for Nginx webapp using Dockerfile" #Prakash Mahajan

on:
  push:
    branches: ["main"]
    # To ignore paths on push, uncomment and correct the following section:
    # paths-ignore:
    #   - "src/"
    tags:
      - 'v1.*'
  pull_request:
    branches: ["main"]

permissions: 
  contents: read

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        # NOTE: Using a stable major version is sufficient.
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Extract metadata for the Docker Image
        id: meta
        # NOTE: Using the latest stable major version tag (@v5) is recommended 
        # for maintenance unless you absolutely need the immutable SHA.
        # uses: docker/metadata-action@v5
        # https://github.com/mahajanP/CICD_Nginx_Dockerfile/commit/
        uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6 

        with:
          # Correct indentation for 'images' parameter
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repository }}
          # Correct indentation for 'tags' multiline string
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}} 
            
      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true 
          # You can use the generated tags from the previous step here if desired:
          # tags: ${{ steps.meta.outputs.tags }}
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-ubuntu:latest
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.respository }}:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}